임시 주문 controller 생성
f-lab-edu/thing-order pull request #2
Opened 2023-04-11 02:27 UTC by hwibaski

2023-04-13 12:09 UTC, f-lab-lyan requested changes
전반적으로 괜찮은 것 같고, Lombok을 적용하고 PR을 머지하면 좋을 것 같습니다.

2023-04-13 12:09 UTC, f-lab-lyan commented on web/src/main/java/org/example/controller/OrderController.java
> +import org.example.dto.order.*;
`*`를 없애주세요.

2023-04-13 12:09 UTC, f-lab-lyan commented on web/src/main/java/org/example/dto/order/ConfirmMemberOrderOutputDTO.java
> +public class ConfirmMemberOrderOutputDTO {
```suggestion
public class ConfirmMemberOrderOutputDto {
```

2023-04-16 10:59 UTC, hwibaski commented on web/src/main/java/org/example/controller/OrderController.java
> +import org.example.dto.order.*;
intellij에서 설정도 변경했고 코드도 변경했습니다!

2023-04-16 10:59 UTC, hwibaski commented on web/src/main/java/org/example/dto/order/ConfirmMemberOrderOutputDTO.java
> +public class ConfirmMemberOrderOutputDTO {
Dto 네이밍 수정했습니다!

2023-04-27 11:43 UTC, f-lab-lyan approved these changes

2023-04-27 11:43 UTC, merged